### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.Int64'

### ISSUE THREAD

**Issue by exy3351** [dornfussenegger/DynamicIL#1]
Sample  ILGenerator.Benchmark

cPerson.AddProperty("TLong", typeof(long));

iPerson.SetPropertyValue("TLong", 2020);

error :  Unable to cast object of type 'System.Int32' to type 'System.Int64'

**Comment by dornfussenegger** [comment]
Hi,
You have to make the conversation by hand. I ve added a test case for that:

        [TestMethod]
        public void TypeOfLongTest()
        {
            CustomTypeCreator ct = new CustomTypeCreator("testassembly");
            var cTest = ct.CreateNewNotifyPropertyChangedType("Test");
            cTest.AddProperty("TLong", typeof(long));
            cTest.AddIPropertyDescriptorImplementation();
            var instance = ct.Build().FirstOrDefault().CreateInstanceWithPropertyGetAndSet();

            instance.SetPropertyValue("TLong", **(long)**2020);

            Assert.IsTrue(instance.**GetPropertyValue<long>("TLong")** == 2020);

        }

You can only set the values with the correct type, and 2020 is an Int32, the long a Int64. If you set the 2020 castet as long, it works as intended.

**Comment by exy3351** [comment]
Ok,  Thank you
